apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafi-gemhar33/simple-node-js-react-npm-app-2.git
    targetRevision: main
    path: kubernetes  # This points to the directory containing your k8s manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources that are no longer defined in Git
      selfHeal: true  # Automatically sync if drift is detected
    syncOptions:
    - CreateNamespace=true